name: Downstream Job

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Project Name'
        required: true
        default: 'a test project'
      labels:
        description: 'Comma Separated list of labels'
        required: true
        default: 'Live Stream'
  repository_dispatch:
    types: [test_suite]

jobs:
  set_vars:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.vars.outputs.project_name }}
      labels: ${{ steps.vars.outputs.labels }}
    steps:
      - name: Set for Repo Dispatch
        id: vars
        run: |
          PROJECT_NAME='${{  github.event.inputs.name }}'
          LABELS='${{ github.event.inputs.labels  }}'
          if [ ${{ github.event_name }} == 'repository_dispatch' ];
          then
            PROJECT_NAME='${{ github.event.client_payload.project_name }}'
            LABELS='${{ github.event.client_payload.labels }}'
          fi
          echo "::set-output name=project_name::${PROJECT_NAME}"
          echo "::set-output name=labels::${LABELS}"
  create_project:
    needs: [set_vars]
    env: # Or as an environment variable
      GITHUBACCESSTOKEN: ${{ secrets.GITHUBACCESSTOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: npm
      #   run: npm ci
      - name: Execute Script
        run: echo '${{ needs.set_vars.outputs.project_name }}' '${{ needs.set_vars.outputs.labels }}'