name: Sample workflow
# This workflow is triggered on pushes to the repository.
on: push
      
jobs:
  build:
    name: Set up Medic on EC2 and Execute Jmeter on another EC2
    runs-on: ubuntu-latest
    steps:
      - name: set tag name
        run: echo "::set-env name=TAG_NAME::${GITHUB_REF#refs/tags/}" 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Echo Dood
        run: ./echo_dood.sh